/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as _appRouteRouteImport } from './pages/__app/route'
import { Route as _appIndexRouteImport } from './pages/__app/index'
import { Route as _authSignInRouteImport } from './pages/__auth/sign-in'

const _appRouteRoute = _appRouteRouteImport.update({
  id: '/__app',
  getParentRoute: () => rootRouteImport,
} as any)
const _appIndexRoute = _appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _appRouteRoute,
} as any)
const _authSignInRoute = _authSignInRouteImport.update({
  id: '/__auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _appIndexRoute
  '/sign-in': typeof _authSignInRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof _authSignInRoute
  '/': typeof _appIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__app': typeof _appRouteRouteWithChildren
  '/__auth/sign-in': typeof _authSignInRoute
  '/__app/': typeof _appIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/'
  id: '__root__' | '/__app' | '/__auth/sign-in' | '/__app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _appRouteRoute: typeof _appRouteRouteWithChildren
  _authSignInRoute: typeof _authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__app': {
      id: '/__app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__app/': {
      id: '/__app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _appIndexRouteImport
      parentRoute: typeof _appRouteRoute
    }
    '/__auth/sign-in': {
      id: '/__auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof _authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface _appRouteRouteChildren {
  _appIndexRoute: typeof _appIndexRoute
}

const _appRouteRouteChildren: _appRouteRouteChildren = {
  _appIndexRoute: _appIndexRoute,
}

const _appRouteRouteWithChildren = _appRouteRoute._addFileChildren(
  _appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _appRouteRoute: _appRouteRouteWithChildren,
  _authSignInRoute: _authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
