/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as _authSignInRouteImport } from './pages/__auth/sign-in'

const _authSignInRoute = _authSignInRouteImport.update({
  id: '/__auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof _authSignInRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof _authSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth/sign-in': typeof _authSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in'
  id: '__root__' | '/__auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authSignInRoute: typeof _authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__auth/sign-in': {
      id: '/__auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof _authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _authSignInRoute: _authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
